### PR TITLE
Add a CloudFormation template for public AWS CI

### PR DESCRIPTION
**Pull request by ararslan**
image

Feedback on the template (and anything else) would be superb, given the above. I've created an AWSCoreJL user as described in [the CloudWatchLogs docs](https://invenia.github.io/CloudWatchLogs.jl/latest/pages/setup.html) and set the credentials in Travis, but I haven't created the stack yet because I want to make sure the template is right first.

### CODE REVIEW

**Comment by ararslan** [comment]
Apparently just having the credentials for a valid AWS account in Travis is enough to get CI to pass? :thinking:

**Comment by omus** [comment]
Looking at the tests it appears AWSCore doesn't do any testing requiring a real AWS account? Have we verified the tests fail with invalid credentials?

**Comment by omus** [comment]
CFN template looks fine. I would probably restrict what stacks it can describe but at this point it isn't a big deal.

**Comment by ararslan** [comment]
> Have we verified the tests fail with invalid credentials?

Running
```julia
withenv("AWS_ACCESS_KEY_ID" => "ABC123", "AWS_SECRET_ACCESS_KEY" => "SHHHHITSASECRET") do
    Pkg.test("AWSCore")
end
```
suggests yes.

**Comment by ararslan** [comment]
Stack created. Anything left to do here for now?

**Comment by omus** [comment]
Documentation?

**Comment by ararslan** [comment]
What part of this would you like documented? The same kind of stuff as in CloudWatchLogs?

**Comment by iamed2** [comment]
Yeah, the docs for this should not assume the docs for CloudWatchLogs.jl exist, and should duplicate information. 

Maybe also give specific instructions for making your tests run on a fork (e.g., make your own stack and set the appropriate environment variables)

**Comment by ararslan** [comment]
I've added documentation with the same content as CloudWatchLogs. It required setting up the Documenter infrastructure, but I didn't do a full doc setup (i.e. linking docstrings and whatnot). I added Eric as a coauthor on the commit since the text was lifted basically wholesale from CWL.

**Review by omus — APPROVED** [review]
That's one great PR for mankind

**Review by iamed2 — APPROVED** [review]

**Comment by omus** [comment]
@ararslan we should make this a PR against AWSCore.jl now?

**Comment by ararslan** [comment]
https://github.com/JuliaCloud/AWSCore.jl/pull/58

**Pull request closed without merging**
